Sprint 7 solution in file manager
nikami-1024/java-kanban pull request #4
Opened 2024-03-17 19:55 UTC by nikami-1024

2024-03-18 19:38 UTC, andrew-larkin requested changes
Привет! Каркас сделан, но впереди еще много работы. Оставил подробные комментарии по коду, если будут возникать вопросы - пиши в личку в Пачке. Тестовый скрипт (названия могут немного отличаться. смысл скрипта - обе распечатки должны быть идентичны)

2024-03-18 19:38 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +    protected String filepath;
лучше использовать класс File - это удобнее и проще. а еще можно использовать модификатор доступа private

2024-03-18 19:38 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +        loadFromFile(this.filepath);
не, из файла здесь пока что ничего не достаем, создание менеджера через конструктор подразумевает, что файл пустой или не сущетсвует

2024-03-18 19:38 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +    private void loadFromFile(String filepath) throws IOException {
вот его можно сделать public. И нужно возвращать новый экземпляр FileBackedTaskManager

2024-03-18 19:38 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +    private void taskFromString(String str) throws IOException {
перенести в CSVParser

2024-03-18 19:38 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +    private void historyFromString(String str) {
перенос

2024-03-18 19:38 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +    private String historyToString() {
перенос

2024-03-18 19:38 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +        try {
лучше сделать выброс и обработку ошибки в самом методе save. тогда не придется в каждом методе обрабатывать его ошибки

2024-03-18 19:38 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +            throw new RuntimeException(e);
и кстати ошибка должна быть ManagerSaveException

2024-03-18 19:38 UTC, andrew-larkin commented on src/manager/InMemoryTaskManager.java
> +    protected void calculateEpicStatus(int epicId) {
а зачем, он ведь автоматически делает свою работу

2024-03-18 19:38 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +
здесь еще не хватает тестового сценария. я скину свой в главном комментарии

2024-03-20 21:40 UTC, nikami-1024 commented on src/manager/FileBackedTaskManager.java
> +    private void historyFromString(String str) {
Чуть улучшила, но не перенесла полностью в CSVParser. Из CSVParser этот метод не может прямо брать задачи из таскменеджеров и писать их в историю.

2024-03-20 22:01 UTC, nikami-1024 commented on src/manager/FileBackedTaskManager.java
> +    private void taskFromString(String str) throws IOException {
Сделала совершенно наоборот %) 
Унесла всю логику обратно в FileBackedTaskManager - заодно починила зааффекченные id для новых тасок.
Внутри CSVParser строка бьётся на части - и всё. Недостаточно круто? Можно лучше и кошернее?

2024-03-20 22:02 UTC, nikami-1024 commented on src/manager/InMemoryTaskManager.java
> +    protected void calculateEpicStatus(int epicId) {
Действительно =) забыла вернуть после каких-то экспериментов/переносов. Спасибо!

2024-03-20 22:46 UTC, nikami-1024 commented on src/manager/FileBackedTaskManager.java
> +    private void loadFromFile(String filepath) throws IOException {
Недореализованная магия [1]

2024-03-20 22:46 UTC, nikami-1024 commented on src/manager/FileBackedTaskManager.java
> +        loadFromFile(this.filepath);
Недореализованная магия [0]

2024-03-21 21:22 UTC, merged